name: distcheck

on:
  push:
    branches: [ "main" ]
  
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Install Doxygen
      run: sudo apt-get install doxygen -y
      shell: bash
      
    - name: Install libbenchmark-dev
      run: sudo apt-get install libbenchmark-dev -y
      shell: bash

    - name: Install ccache
      uses: hendrikmuhs/ccache-action@v1.2.8

    - uses: actions/checkout@v3

    - name: bootstrap
      run: ./bootstrap

    - name: Setup PATH
      run: echo "PATH=/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH" >> $GITHUB_ENV

    - name: configure
      run: ./configure
      
    - name: make check
      run: make check

    - name: make distcheck
      run: |
        echo $PATH
        make distcheck
