name: Automake distcheck

on:
  push:
    branches: [ "main" ]
  
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: bootstrap
      run: ./bootstrap

    - name: configure
      run: ./configure

    - name: make distcheck
      run: make distcheck
