name: distcheck

on:
  push:
    branches: [ "main" ]
  
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      packages: doxygen libbenchmark-dev
      
#      run: sudo apt-get install -y doxygen libbenchmark-dev

    - uses: actions/checkout@v3

    - name: Bootstrap
      run: ./bootstrap

    - name: Configure
      run: ./configure
      
    - name: Build
      run: make check
